version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

apt_packages:
  - plantuml

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt

submodules:
  include:
    - docs/source/_external/basyx-java-server-sdk
  recursive: true
